<style type="text/css">
    dl {
        padding-bottom: 50px;
        clear: both;
    }
    dt {
        display: block;
        float: left;
        clear: both;
        padding-right: 20px;
        min-width: 80px;
    }
    dd {
        margin-left: 100px;
        overflow: hidden;
    }
    img {
        display: block;
        float: left;
        margin: 0 2px;
    }
</style>
<?php
if (!empty($this->list)):
    foreach($this->list as /** @var Model_ShopProduct $product */$product):
    $images = $product->getImages();
    ?>
<dl>
    <dt>Title:</dt>
    <dd><a href="<?=$product->getUrl()?>" target="_blank"><?=$product->getTitle()?></a></dd>
    <dt>Price:</dt>
    <dd><?=$product->getPrice()?></dd>
    <dt>Description:</dt>
    <dd><?=$product->getDescription()?>&nbsp;</dd>
    <?php if (count($images) > 0): ?>
    <dt>Images:</dt>
    <dd>
        <?php foreach($images as $img): ?>
        <img src="<?=$img?>" alt="<?=$product->getTitle()?>">
        <?php endforeach; ?>
    </dd>
    <?php endif; ?>
    <dt>Extra:</dt>
    <dd><pre><?php print_r($product->getAttribs()); ?></pre></dd>
</dl>
<?php
    endforeach;
else:
?>
    <div>No data</div>
<?php
endif;
?>


<pre>
<?php @print_r($this->debug); ?>
</pre>