<style type="text/css">
    dl {
        overflow: hidden;
    }
    dt, dd {
        float: left;
    }
    dt {
        clear: both;
    }
</style>
<?php foreach($this->list as /** @var Model_Finder_Product $product */$product):
    $images = $product->getImages();
    ?>
<div>
    <dl>
        <dt>Title:</dt>
        <dd><a href="<?=$product->getUrl()?>" target="_blank"><?=$product->getTitle()?></a></dd>
        <dt>Price:</dt>
        <dd><?=$product->getPrice()?></dd>
        <dt>Description:</dt>
        <dd><?=$product->getDescription()?></dd>
        <?php if (count($images) > 0): ?>
        <dt>Images:</dt>
        <dd>
            <?php foreach($images as $img): ?>
            <img src="<?=$img?>" alt="<?=$product->getTitle()?>">
            <?php endforeach; ?>
        </dd>
        <?php endif; ?>
    </dl>
</div>
<?php endforeach; ?>

<pre>
<?php @print_r($this->debug); ?>
</pre>