<style type="text/css">
    dl {
        padding-bottom: 50px;
        clear: both;
    }
    dt {
        display: block;
        float: left;
        clear: both;
        padding-right: 20px;
        min-width: 80px;
    }
    dd {
        margin-left: 100px;
        overflow: hidden;
    }
    img {
        display: block;
        float: left;
        margin: 0 2px;
    }
    .html_pres {
        background-color: #EEEEEE;
    }
    .html_src {
        background-color: #EEEEFF;
        font-family: monospace;
        font-size: 12px;
    }
</style>
<?php
if (!empty($this->list)):
    foreach($this->list as /** @var Model_Finder_Product $product */$product):
    $images = $product->getImages();
    ?>
<dl>
    <dt>Title:</dt>
    <dd><a href="<?=$product->getUrl()?>" target="_blank"><?=$product->getTitle()?></a></dd>
    <dt>Price:</dt>
    <dd><?=$product->getPrice()?></dd>
    <dt>Description:</dt>
    <dd><?=$product->getDescription()?>&nbsp;</dd>
    <?php if (count($images) > 0): ?>
    <dt>Images:</dt>
    <dd>
        <?php foreach($images as $img): ?>
        <img src="<?=$img?>" alt="<?=$product->getTitle()?>">
        <?php endforeach; ?>
    </dd>
    <?php endif; ?>
    <dt>Extra:</dt>
    <dd><pre><?php echo htmlentities(print_r($product->getAttribs(), true)); ?></pre></dd>
</dl>
<?php
    endforeach;
else:
?>
    <div>No data</div>
<?php
endif;
?>

<?php if (!empty($this->debug)): ?>
<pre><?php echo htmlentities(print_r($this->debug, true)); ?></pre>
<?php endif; ?>

<?php if (!empty($this->show)): ?>
<fieldset class="html_pres">
  <legend>HTML presentation</legend>
  <?php echo$this->show; ?>
</fieldset>
<fieldset class="html_src">
  <legend>Source code</legend>
  <?php echo nl2br(htmlentities($this->show)); ?>
</fieldset>
<?php endif; ?>
