<style type="text/css">
    dl {
        overflow: hidden;
    }
    dt, dd {
        float: left;
    }
    dt {
        clear: both;
    }
</style>
<?php foreach($this->products as /** @var Model_ShopProduct $product */$product): ?>
<div>
    <dl>
        <dt>Title:</dt>
        <dd><?=$product->title?></dd>
        <dt>Price:</dt>
        <dd><?=$product->price?></dd>
        <dt>Description:</dt>
        <dd><?=$product->description?></dd>
    </dl>
</div>
<?php endforeach; ?>