<a href = "<?php echo $this->url(array(), 'default', true) ?>">Главная</a>
<a href = "<?php echo $this->url(array('page' => 1),'ebay'); ?>">Test <b>eBay</b> [1]</a>
<a href = "<?php echo $this->url(array('page' => 2),'ebay'); ?>">Test <b>eBay</b> [2]</a>
<a href = "<?php echo $this->url(array('page' => 1),'shoppingcom'); ?>">Test <b>shopping.com</b> [1]</a>
<a href = "<?php echo $this->url(array('page' => 2),'shoppingcom'); ?>">Test <b>shopping.com</b> [2]</a>

